import React, { useState } from 'react';
import { Sparkles, Coins, Map, Dice6, Loader2 } from 'lucide-react';
import { generateAIGent } from '@/app/actions'; // Import our new brain

const GeneratorHub = () => {
  const [result, setResult] = useState<any>(null);
  const [type, setType] = useState('encounter');
  const [isLoading, setIsLoading] = useState(false);

  const handleGenerate = async (category: string) => {
    setIsLoading(true);
    // Call the server action directly
    const response = await generateAIGent(type as any, category);
    
    setResult({
      type: type === 'encounter' ? 'AI Encounter' : 'AI Loot',
      title: category,
      text: response.text
    });
    setIsLoading(false);
  };
  const handleExport = () => {
  if (!result) return;

  const fileName = `${result.type.replace(/\s+/g, '_')}_${result.title}.md`;
  const content = `# ${result.type}: ${result.title}\n\n${result.text}\n\n--- \nGenerated by AEGIS DM Assistant`;

  const element = document.createElement("a");
  const file = new Blob([content], { type: 'text/markdown' });
  element.href = URL.createObjectURL(file);
  element.download = fileName;
  document.body.appendChild(element); // Required for this to work in FireFox
  element.click();
  document.body.removeChild(element);
};

// Inside your GeneratorHub component...

  return (
    <div className="flex flex-col gap-4 bg-stone-900/60 p-6 rounded-xl border border-amber-900/30 h-full relative min-h-[400px]">
      {/* Loading Overlay */}
      {isLoading && (
        <div className="absolute inset-0 bg-stone-950/50 backdrop-blur-[1px] z-20 flex items-center justify-center rounded-xl">
          <Loader2 className="text-amber-500 animate-spin" size={32} />
        </div>
      )}

      <h2 className="text-xl text-amber-500 font-serif flex items-center gap-2">
        <Dice6 size={20} className="text-amber-600" /> AI Generator Hub
      </h2>

      {/* TABS: Make sure these update the 'type' state */}
      <div className="flex gap-2 mb-2">
        <button 
          onClick={() => { setType('encounter'); setResult(null); }}
          className={`flex-1 py-2 text-xs rounded border transition-all ${type === 'encounter' ? 'bg-amber-900/40 border-amber-600 text-amber-200' : 'bg-stone-800 border-stone-700 text-stone-500'}`}
        >
          Encounters
        </button>
        <button 
          onClick={() => { setType('loot'); setResult(null); }}
          className={`flex-1 py-2 text-xs rounded border transition-all ${type === 'loot' ? 'bg-amber-900/40 border-amber-600 text-amber-200' : 'bg-stone-800 border-stone-700 text-stone-500'}`}
        >
          Loot Table
        </button>
      </div>

      <div className="flex-1 space-y-2">
        {/* ENCOUNTER VIEW */}
        {type === 'encounter' && (
          <div className="grid grid-cols-2 gap-2 animate-in fade-in duration-300">
            {["Forest", "Dungeon", "Urban", "Arctic", "Underdark"].map(env => (
              <button 
                key={env} 
                onClick={() => handleGenerate(env)}
                className="p-2 bg-stone-800 hover:bg-stone-700 text-stone-300 text-medium rounded border border-stone-700 flex items-center gap-2"
              >
                <Map size={14} /> {env}
              </button>
            ))}
          </div>
        )}

        {/* LOOT VIEW: Ensure this block is visible when type is 'loot' */}
        {type === 'loot' && (
          <div className="flex flex-col gap-2 animate-in fade-in duration-300">
            {["Low", "Mid", "High"].map(tier => (
              <button 
                key={tier} 
                onClick={() => handleGenerate(tier)}
                className="p-2 bg-stone-800 hover:bg-stone-700 text-stone-300 text-medium rounded border border-stone-700 flex items-center gap-2"
              >
                <Coins size={12} /> {tier} Tier Loot
              </button>
            ))}
            <p className="text-[10px] text-stone-500 italic px-1">Select a tier to generate unique AI treasure.</p>
          </div>
        )}
{/* UNIFIED RESULT BOX */}
{result && !isLoading && (
  <div className="mt-4 p-4 bg-amber-950/20 border border-amber-900/40 rounded-lg animate-in slide-in-from-bottom-2 duration-500">
    
    {/* HEADER ROW: Title on left, Download on right */}
    <div className="flex justify-between items-center mb-3 pb-2 border-b border-amber-900/20">
      <span className="text-[14px] uppercase tracking-widest text-amber-600 font-bold">
        {result.type}: {result.title}
      </span>
      
      <button 
        onClick={handleExport}
        className="text-[14px] text-amber-500 hover:text-amber-400 hover:bg-amber-900/20 flex items-center gap-1 border border-amber-900/40 px-2 py-1 rounded bg-stone-900 transition-colors"
      >
        Download .MD
      </button>
    </div>

    {/* CONTENT AREA */}
    <div className="text-medium text-stone-200 leading-relaxed max-w-none">
      <p className="whitespace-pre-wrap italic">
        {result.text}
      </p>
    </div>
  </div>
)}
          </div>
        </div>
  );
};
export default GeneratorHub;